-- MySQL Script generated by MySQL Workbench
-- Tue 22 Nov 2016 11:39:12 PM BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bancodb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bancodb` ;

-- -----------------------------------------------------
-- Schema bancodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancodb` DEFAULT CHARACTER SET utf8 ;
USE `bancodb` ;

-- -----------------------------------------------------
-- Table `bancodb`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancodb`.`autor` ;

CREATE TABLE IF NOT EXISTS `bancodb`.`autor` (
  `ID_AUTOR` INT(11) NOT NULL,
  `Nome` VARCHAR(45) NULL DEFAULT NULL,
  `NomeFantasia` VARCHAR(45) NULL DEFAULT NULL,
  `Nacionalidade` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_AUTOR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodb`.`categoria_item_acervo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancodb`.`categoria_item_acervo` ;

CREATE TABLE IF NOT EXISTS `bancodb`.`categoria_item_acervo` (
  `ID_CAT` INT(11) NOT NULL,
  `NomeCategoria` VARCHAR(45) NULL DEFAULT NULL,
  `Descricao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CAT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancodb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bancodb`.`usuario` (
  `ID_USU` INT(11) NOT NULL,
  `Nivel_De_Acesso` ENUM('Adminstrador', 'Funcionario', 'Professor') NULL DEFAULT NULL,
  `Nome` VARCHAR(45) NULL DEFAULT NULL,
  `CPF` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `NumeroResidencial` VARCHAR(45) NULL DEFAULT NULL,
  `NumeroCelular` VARCHAR(45) NULL DEFAULT NULL,
  `NumeroComercial` VARCHAR(45) NULL DEFAULT NULL,
  `MatriculaEducacional` VARCHAR(45) NULL DEFAULT NULL,
  `Senha` VARCHAR(45) NULL DEFAULT NULL,
  `endereco_Logadouro` VARCHAR(45) NULL DEFAULT NULL,
  `endereco_CEP` VARCHAR(45) NULL DEFAULT NULL,
  `endereco_Cidade` VARCHAR(45) NULL DEFAULT NULL,
  `endereco_Estado` VARCHAR(45) NULL DEFAULT NULL,
  `endereco_Pais` VARCHAR(45) NULL DEFAULT NULL,
  `StatusDoUsuario` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_USU`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `NumeroResidencial_UNIQUE` (`NumeroResidencial` ASC),
  UNIQUE INDEX `NumeroCelular_UNIQUE` (`NumeroCelular` ASC),
  UNIQUE INDEX `NumeroComercial_UNIQUE` (`NumeroComercial` ASC),
  UNIQUE INDEX `MatriculaEducacional_UNIQUE` (`MatriculaEducacional` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodb`.`emprestimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancodb`.`emprestimo` ;

CREATE TABLE IF NOT EXISTS `bancodb`.`emprestimo` (
  `ID_EMP` INT(11) NOT NULL,
  `DataEmprestimo` DATE NULL DEFAULT NULL,
  `DataPrevDevolucao` DATE NULL DEFAULT NULL,
  `DataDevolucao` DATE NULL DEFAULT NULL,
  `ValorMulta` DECIMAL(10,0) NULL DEFAULT NULL,
  `Situacao` ENUM('Aberto', 'Fechado', 'Em Andamento', 'Reserva', 'Atrasado', 'Cancelado') NOT NULL,
  `Reserva` TINYINT(1) NULL DEFAULT '0',
  `FK_Funcionario` INT(11) NOT NULL,
  `FK_USU` INT(11) NOT NULL,
  PRIMARY KEY (`ID_EMP`, `FK_Funcionario`, `FK_USU`),
  INDEX `fk_Emprestimo_Usuario1_idx` (`FK_Funcionario` ASC),
  INDEX `fk_Emprestimo_Usuario2_idx` (`FK_USU` ASC),
  CONSTRAINT `fk_Emprestimo_Usuario1`
    FOREIGN KEY (`FK_Funcionario`)
    REFERENCES `bancodb`.`usuario` (`ID_USU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Emprestimo_Usuario2`
    FOREIGN KEY (`FK_USU`)
    REFERENCES `bancodb`.`usuario` (`ID_USU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodb`.`produtoraconteudo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancodb`.`produtoraconteudo` ;

CREATE TABLE IF NOT EXISTS `bancodb`.`produtoraconteudo` (
  `ID_PDC` INT(11) NOT NULL,
  `Nome_Produtora` VARCHAR(45) NULL DEFAULT NULL,
  `Descricao` VARCHAR(45) NULL DEFAULT NULL,
  `CNPJ` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PDC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodb`.`titulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancodb`.`titulo` ;

CREATE TABLE IF NOT EXISTS `bancodb`.`titulo` (
  `ID_TITU` INT(11) NOT NULL,
  `ISBN` VARCHAR(45) NULL DEFAULT NULL,
  `ISSN` VARCHAR(45) NULL DEFAULT NULL,
  `obra` VARCHAR(45) NULL DEFAULT NULL,
  `Descricao` VARCHAR(45) NULL DEFAULT NULL,
  `DataDePublicacao` DATE NULL DEFAULT NULL,
  `CidadePublicacao` VARCHAR(45) NULL DEFAULT NULL,
  `EstadoPublicacao` VARCHAR(45) NULL DEFAULT NULL,
  `Edicao` VARCHAR(45) NULL DEFAULT NULL,
  `Idioma` VARCHAR(45) NULL DEFAULT NULL,
  `Traducao` VARCHAR(45) NULL DEFAULT NULL,
  `Capa` VARCHAR(45) NULL DEFAULT NULL,
  `FK_ITEM_PDC` INT(11) NOT NULL,
  `FK_CAT_ARCE` INT(11) NOT NULL,
  PRIMARY KEY (`ID_TITU`, `FK_ITEM_PDC`, `FK_CAT_ARCE`),
  INDEX `fk_Titulo_ProdutoraConteudo1_idx` (`FK_ITEM_PDC` ASC),
  INDEX `fk_Titulo_Categoria_item_acervo1_idx` (`FK_CAT_ARCE` ASC),
  CONSTRAINT `fk_Titulo_Categoria_item_acervo1`
    FOREIGN KEY (`FK_CAT_ARCE`)
    REFERENCES `bancodb`.`categoria_item_acervo` (`ID_CAT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Titulo_ProdutoraConteudo1`
    FOREIGN KEY (`FK_ITEM_PDC`)
    REFERENCES `bancodb`.`produtoraconteudo` (`ID_PDC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodb`.`exemplar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancodb`.`exemplar` ;

CREATE TABLE IF NOT EXISTS `bancodb`.`exemplar` (
  `ID_EXE` INT(11) NOT NULL,
  `ISBN` VARCHAR(45) NULL DEFAULT NULL,
  `LiberadoParaEmprestimo` TINYINT(1) NULL DEFAULT '1',
  `Duracao` VARCHAR(45) NULL DEFAULT NULL,
  `QuantidadePaginas` VARCHAR(45) NULL DEFAULT NULL,
  `FK_TITULO` INT(11) NOT NULL,
  PRIMARY KEY (`ID_EXE`, `FK_TITULO`),
  INDEX `fk_Exemplar_Titulo1_idx` (`FK_TITULO` ASC),
  CONSTRAINT `fk_Exemplar_Titulo1`
    FOREIGN KEY (`FK_TITULO`)
    REFERENCES `bancodb`.`titulo` (`ID_TITU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodb`.`titulo_tem_autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancodb`.`titulo_tem_autor` ;

CREATE TABLE IF NOT EXISTS `bancodb`.`titulo_tem_autor` (
  `Titulo_idTitulo` INT(11) NOT NULL,
  `Autor_idAutor` INT(11) NOT NULL,
  `TipoDeAutor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Titulo_idTitulo`, `Autor_idAutor`),
  INDEX `fk_Titulo_has_Autor_Autor1_idx` (`Autor_idAutor` ASC),
  INDEX `fk_Titulo_has_Autor_Titulo1_idx` (`Titulo_idTitulo` ASC),
  CONSTRAINT `fk_Titulo_has_Autor_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `bancodb`.`autor` (`ID_AUTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Titulo_has_Autor_Titulo1`
    FOREIGN KEY (`Titulo_idTitulo`)
    REFERENCES `bancodb`.`titulo` (`ID_TITU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodb`.`exemplar_contem_emprestimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancodb`.`exemplar_contem_emprestimo` ;

CREATE TABLE IF NOT EXISTS `bancodb`.`exemplar_contem_emprestimo` (
  `FK_exemplar_ID_EXE` INT(11) NOT NULL,
  `FK_emprestimo_ID_EMP` INT(11) NOT NULL,
  `status_exemplar` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`FK_exemplar_ID_EXE`, `FK_emprestimo_ID_EMP`),
  INDEX `fk_exemplar_has_emprestimo_emprestimo1_idx` (`FK_emprestimo_ID_EMP` ASC),
  INDEX `fk_exemplar_has_emprestimo_exemplar1_idx` (`FK_exemplar_ID_EXE` ASC),
  CONSTRAINT `fk_exemplar_has_emprestimo_exemplar1`
    FOREIGN KEY (`FK_exemplar_ID_EXE`)
    REFERENCES `bancodb`.`exemplar` (`ID_EXE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exemplar_has_emprestimo_emprestimo1`
    FOREIGN KEY (`FK_emprestimo_ID_EMP`)
    REFERENCES `bancodb`.`emprestimo` (`ID_EMP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
